version: 2
jobs:
  build:
    docker:
      - image: terrorjack/pixie

    steps:
      - run:
          name: Initialize nix environment
          command: |
            nix-env -f "<nixpkgs>" -iA haskellPackages.Agda gitMinimal openssh
            agda --version
      - checkout

      # - run:
      #     name: Install Agda
      #     command: |
      #       stack --resolver nightly install alex cpphs happy Agda
      #       agda --version
      #     no_output_timeout: 1.2h

      - run:
          name: Install the Agda Standard lib
          command: |
            git clone https://github.com/agda/agda-stdlib.git ~/agda-stdlib/
            mkdir ~/.agda
            echo "~/agda-stdlib/standard-library.agda-lib" >> ~/.agda/libraries
            echo "standard-library" >> ~/.agda/defaults
      - run:
          name: Build (almost) the whole development
          command: agda src/Schedule.agda

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test
