version: 2
jobs:
  build:
    docker:
      - image: terrorjack/pixie

    steps:
      - run:
          name: Initialize nix environment
          command: |
            nix-channel --add https://nixos.org/channels/nixpkgs-unstable && nix-channel --update
            nix-env -iA nixpkgs.haskellPackages.Agda nixpkgs.gitMinimal nixpkgs.openssh
            agda --version
      - checkout

      # - run:
      #     name: Install Agda
      #     command: |
      #       stack --resolver nightly install alex cpphs happy Agda
      #       agda --version
      #     no_output_timeout: 1.2h

      - run:
          name: Install the Agda Standard lib
          command: |
            git clone https://github.com/agda/agda-stdlib.git ~/agda-stdlib/
            mkdir ~/.agda
            echo "~/agda-stdlib/standard-library.agda-lib" >> ~/.agda/libraries
            echo "standard-library" >> ~/.agda/defaults
      - run:
          name: Build (almost) the whole development
          working_directory: src
          command: agda Schedule.agda

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#      - test
